### ISSUE TITLE
npcap & rpcapd support

### ISSUE THREAD

**Issue by ether42** [nmap/npcap#74]
Hi there,

I gave a try at [rpcapd](https://www.winpcap.org/docs/docs_40_2/html/group__remote.html) (via [WinPCAP](https://www.winpcap.org/) on Windows and [libpcap](https://github.com/the-tcpdump-group/libpcap) master on Linux) and it seemed to fit our usage nicely. It seems broken (it probably worked one time out of ten and when it doesn't it reports some number of packets but won't forward them) on Windows 2016 (and probably Windows 10 from some reports I saw) but works fine on Windows 2012.

I quickly looked at different mailing lists & issues trackers hoping the problem was already reported or known and I stumbled on [npcap](https://github.com/nmap/npcap).

WinPCAP seems frozen and I don't have much hope to make it work out the box without probably having to debug/recompile it (and I'll probably have issues later since I won't be able to sign it? I'm not well versed in Windows development, sorry :)).
Installing npcap in WinPCAP compatibility mode will make `rpcapd.exe` simply quit immediately and there doesn't seem to be an rpcapd server embedded with npcap.

Do you have any plans to provide rpcapd (which is now available from libpcap with `configure --enable-remote`) and the corresponding service or do you have any clue why npcap's compatibility mode seems to make `rpcapd.exe` from WinPCAP exit?

Thanks!

Regards.

**Comment by chmorgan** [comment]
Is it straightforward to update the installer to include rpcapd.exe? I'm testing the latest npcap version with SharpPcap and the remote tests started failing and found this issue. If I had a few pointers I could open a PR to include those files.

**Comment by aslgithub** [comment]
@guyharris @dmiller-nmap Is it possible to get rpcapd included in the npcap installer if its being built please?
From Guy's comments looks like the actual build was fixed in 2019..
It would be great to move to npcap, but the lack of this support prevents this.
Thanks !

**Comment by daluu** [comment]
FYI, I followed the instructions for building libpcap to get rpcapd, and the additional comments from Guy here is a bit helpful, but all that is still not enough to actually deploy rpcapd.

To at least run `rpcapd -h` without issue, you have to follow this guide: https://omnine.blogspot.com/2020/08/wireshark-remote-capture-with-rpcapd.html for the remaining steps. Note that you don't actually need to put rpcapd under Npcap folder, but I assume that's just by convention.

All that is necessary for the npcap installer to perform to replicate what Winpcap installer used to do. And the registry step would be needed if we wish to replicate what Winpcap offered in automatically setting up the rpcapd as a Windows service I think.

**Comment by daluu** [comment]
For consideration of this issue request, it would be nice if npcap project can consider https://github.com/nmap/npcap/issues/721 as well so that the included rpcapd would have TLS support, and that Wireshark then can also get TLS support on the rpcap client side, but I think it would require updates to Wireshark GUI codebase (and tshark/wireshark/dumpcap CLI codebase) to make use (or availability) of the TLS feature when available in the underlying libpcap/npcap dependency.
